$( document ).ready(function() {
	var aboutUsHTML = '<div class="uk-section uk-section-large"><div class="uk-container"><h1>Davison Menswear & Kilt Hire<br/>Established 1927.</h1><div class="uk-grid-match uk-child-width-1-2@m" uk-grid><div><p>';
	aboutUsHTML += 'Welcome to Davison kilt hire, suppliers of the highest quality Highland & formal dress. Established in 1927 we are experienced in supplying all your needs in Scottish outfitting. <br/><br/>We believe in only supplying the best of the best and will not settle for cheap imitations so neither should our customers. When it comes to looking for a quality product with service to match, look no further.'
	aboutUsHTML += '</p></div><div><img data-src="images/bagpipes.jpg" style="height: 100%;" alt="" uk-img></div></div></div></div>';
	
	var infoHTML = '<div class="uk-section uk-section-large" style="height:100%"><div class="uk-container" style="height:100%">'
	infoHTML += '<h1>Davison Menswear & Kilt Hire</h1><div class="uk-grid-match uk-child-width-1-2@m" uk-grid style="height:100%; max-height: 450px;"><div style="height:100%">';
	infoHTML += '<div><h3>Opening Times</h3>'
	infoHTML+='<table class="uk-table">'
	infoHTML+='<tbody>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Monday</td>'
	infoHTML+='<td class="time">9.30am - 6pm</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Tuesday</td>'
	infoHTML+='<td class="time">9.30am - 6pm</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Wednesday</td>'
	infoHTML+='<td class="time">9.30am - 6pm</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Thursday</td>'
	infoHTML+='<td class="time">9.30am - 8pm</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Friday</td>'
	infoHTML+='<td class="time">9.30am - 6pm</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Saturday</td>'
	infoHTML+='<td class="time">9.30am - 5pm</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td class="day">Sunday</td>'
	infoHTML+='<td class="time">11am - 4pm</td>'
	infoHTML+='</tr>'
	infoHTML+='</tbody>'
	infoHTML+='</table>'
	infoHTML+='<button class="uk-button uk-button-default uk-margin-small-right" type="button" uk-toggle="target: #contact">Contact Us</button>'
	infoHTML+='<div id="contact" uk-modal>'
	infoHTML+='<div class="uk-modal-dialog uk-modal-body"style="background-color: black;border: 1px solid white;">'
	infoHTML+='<div id="body">'
	infoHTML+='<div class="contact">'
	infoHTML+='<h1>contact us</h1>'
	infoHTML+='<p>Feel free to fill in the form below if you have any enquiries. Alternatively you can call us on 0131 229 0266 or out of hours on 07766 552 930.</p>'
	infoHTML+='<form name="contactform" method="post" action="send_form_email.php">'
	infoHTML+='<table width="450px" align="center">'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td valign="top">'
	infoHTML+='<label for="first_name">First Name</label></td>'
	infoHTML+='<td valign="top">'
	infoHTML+='<input  type="text" name="first_name" maxlength="50" size="30">'
	infoHTML+='</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td valign="top"">'
	infoHTML+='<label for="last_name">Last Name</label>'
	infoHTML+='</td>'
	infoHTML+='<td valign="top">'
	infoHTML+='<input  type="text" name="last_name" maxlength="50" size="30">'
	infoHTML+='</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td valign="top">'
	infoHTML+='<label for="email">Email Address</label>'
	infoHTML+='</td>'
	infoHTML+='<td valign="top">'
	infoHTML+='<input  type="text" name="email" maxlength="80" size="30">'
	infoHTML+='</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td valign="top">'
	infoHTML+='<label for="telephone">Telephone Number</label>'
	infoHTML+='</td>'
	infoHTML+='<td valign="top">'
	infoHTML+='<input  type="text" name="telephone" maxlength="30" size="30">'
	infoHTML+='</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td valign="top">'
	infoHTML+='<label for="comments">Enquiry</label>'
	infoHTML+='</td>'
	infoHTML+='<td valign="top">'
	infoHTML+='<textarea  name="comments" cols="22" rows="6"></textarea>'
	infoHTML+='</td>'
	infoHTML+='</tr>'
	infoHTML+='<tr>'
	infoHTML+='<td colspan="2" style="text-align:center">'
	infoHTML+='<input type="submit" value="Submit"></td>'
	infoHTML+='</tr>'
	infoHTML+='</table>'
	infoHTML+='</form>'
	infoHTML+='</div>'
	infoHTML+='</div>'
	infoHTML+='</div>'
	infoHTML+='</div>'
	infoHTML+='</div>'
	infoHTML += '</div><div style="height:100%"><iframe style="height:100%" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8938.275654656887!2d-3.204802!3d55.9395108!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1d0675edf90601c9!2sDavison+Menswear!5e0!3m2!1sen!2suk!4v1527535608538"  frameborder="0" allowfullscreen></iframe></div></div></div></div>';

	var servicesHTML = '<div style="padding: 10px; height:100%" class="uk-child-width-1-3@m" uk-grid uk-scrollspy="cls: uk-animation-fade; target: > div > .uk-card; delay: 500; repeat: true">'
	servicesHTML+= "<div style='height:100%'>"
	servicesHTML+= '<div class="uk-card uk-card-default uk-card-body">'
	servicesHTML+= '<h3 class="uk-card-title">Suits</h3>'
	servicesHTML+= '<img class="serviceImg" src="images/suit1.jpg"/>'
	servicesHTML+= "<ul style='padding: 0px;'><li>Morning Suits</li><li>Shirts</li><li>Jackets</li><li>Dinner Suits</li></ul>"
	servicesHTML+= "</div>"
	servicesHTML+= "</div>"
	servicesHTML+= "<div style='height:100%'>"
	servicesHTML+= '<div class="uk-card uk-card-default uk-card-body">'
	servicesHTML+= '<h3 class="uk-card-title">Kilts</h3>'
	servicesHTML+= '<img class="serviceImg" src="images/kilt1.jpg"/>'
	servicesHTML+= "<ul style='padding: 0px;'><li>Kilt Hire</li><li>Sporrans</li><li>Tartans</li></ul>"
	servicesHTML+= "</div>"
	servicesHTML+= "</div>"
	servicesHTML+= "<div style='height:100%'>"
	servicesHTML+= '<div class="uk-card uk-card-default uk-card-body">'
	servicesHTML+= '<h3 class="uk-card-title">Misc</h3>'
	servicesHTML+= '<img class="serviceImg" src="images/shoes2.jpg"/>'
	servicesHTML+= "<ul style='padding: 0px;'><li>Shoes</li><li>Buckles</li><li>Ex Hire Sales</li><li>Measauring</li></ul>"
	servicesHTML+= "</div>"
	servicesHTML+= "</div>"
	servicesHTML+= "</div>"

	var classySporran = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Dress Sporrans</h1><div uk-slider="finite: true">'
	classySporran += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	classySporran += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress1.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW1 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress2.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW2 Cone Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress3.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW3K Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress4.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW3K Interlink Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress5.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW6D Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress6.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW6G Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress7.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW2AT Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress8.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW2AT Masonic Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress9.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW3K Graphite Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress10.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW2 Black Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress11.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>EW3K Black Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress12.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES2 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress13.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES3 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress14.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES4 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress15.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES6 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress16.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES8 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress17.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES9 Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress18.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES1 Thistle Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress19.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES3 Lion Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress20.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES3 Stag Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '<li class="uk-transition-toggle">'
	classySporran += '<img src="images/dress/dress21.jpg" alt="">'
	classySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES1 Masonic Chrome</h3></div>'
	classySporran += '</li>'
	classySporran += '</ul>'
	classySporran += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	classySporran += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	classySporran += '</div>'
	classySporran += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	classySporran += '</div></div></div>'

	var semiSporran = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Semi-Dress Sporrans</h1><div uk-slider="finite: true">'
	semiSporran += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	semiSporran += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi1.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SHEP</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi2.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZD-SHEP</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi3.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>BT-SC</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi4.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZD-SHEP Special</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi5.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>CBFS-1</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi6.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>CBFS-2</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi7.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Antique Blackskin</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi8.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>CBFS-D</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi9.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SP-S</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi10.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>JM-PS Thistle</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi11.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>JM-PS Lion</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi12.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SH-EP Special</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi13.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>HS-PT</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi14.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-TS</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi15.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-JS</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi16.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-HS</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi17.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-TS Antique Blackskin</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi18.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SH-EP Special Blackskin</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi19.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>CBFS-2 Blackskin</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi20.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>BT-SC Blackskin</h3></div>'
	semiSporran += '</li>'
	semiSporran += '<li class="uk-transition-toggle">'
	semiSporran += '<img src="images/semi/semi21.jpg" alt="">'
	semiSporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZD Special Blackskin</h3></div>'
	semiSporran += '</li>'
	semiSporran += '</ul>'
	semiSporran += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	semiSporran += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	semiSporran += '</div>'
	semiSporran += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	semiSporran += '</div></div></div>'

	var daySporran = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Day Sporrans</h1><div uk-slider="finite: true">'
	daySporran += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	daySporran += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day1.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>8GS</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day2.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZD</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day3.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SM</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day4.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SP</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day5.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>STM</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day6.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>HB</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day7.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>BT</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day8.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>BF</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day9.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>HS</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day10.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>JMP</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day11.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>GTSF</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day12.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>HS-TB</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day13.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-J</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day14.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-T</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day15.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>DP-H</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day16.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZSF-1</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day17.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZSF-2</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day18.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZSF-3</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day19.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SP-J</h3></div>'
	daySporran += '</li>'
	daySporran += '<li class="uk-transition-toggle">'
	daySporran += '<img src="images/day/day20.jpg" alt="">'
	daySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SP-T</h3></div>'
	daySporran += '</li>'
	daySporran += '</ul>'
	daySporran += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	daySporran += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	daySporran += '</div>'
	daySporran += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	daySporran += '</div></div></div>'

	var boySporran = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Boys Sporrans</h1><div uk-slider="finite: true">'
	boySporran += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	boySporran += '<ul class="uk-slider-items uk-child-width-1-1 uk-child-width-1-3@s uk-child-width-1-3@m uk-grid">'
	boySporran += '<li class="uk-transition-toggle">'
	boySporran += '<img src="images/boy/boy1.jpg" alt="">'
	boySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>8GS</h3></div>'
	boySporran += '</li>'
	boySporran += '<li class="uk-transition-toggle">'
	boySporran += '<img src="images/boy/boy2.jpg" alt="">'
	boySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>AZD</h3></div>'
	boySporran += '</li>'
	boySporran += '<li class="uk-transition-toggle">'
	boySporran += '<img src="images/boy/boy3.jpg" alt="">'
	boySporran += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SM</h3></div>'
	boySporran += '</li>'
	boySporran += '</ul>'
	boySporran += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	boySporran += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	boySporran += '</div>'
	boySporran += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	boySporran += '</div></div></div>'

	var tartanHTML = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Tartans</h1><div uk-slider="finite: true">'
	tartanHTML += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	tartanHTML += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan1.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Davidson Modern</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan2.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Gordon Modern</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan3.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Mackenzie Modern</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan4.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Sutherland Ancient</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan5.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>MacDonald of the Isles</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan6.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Fraser Ancient</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan7.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Gunn Modern</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan8.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Gunn Ancient</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan9.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Campbell of Argyll</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '<li class="uk-transition-toggle">'
	tartanHTML += '<img src="images/tartan/tartan10.jpg" alt="">'
	tartanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Douglas Green Modern</h3></div>'
	tartanHTML += '</li>'
	tartanHTML += '</ul>'
	tartanHTML += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	tartanHTML += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	tartanHTML += '</div>'
	tartanHTML += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	tartanHTML += '</div><p>Can\'t find your tartan? Click <a target="_blank" href="http://www.tartansauthority.com/tartan-ferret/">here</a></p></div></div>'

	var beltHTML = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Belts</h1><div uk-slider="finite: true">'
	beltHTML += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	beltHTML += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt1.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Unlined Belt</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt2.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Lined Belt</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt3.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Velcro Belt</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt4.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Khaki Pigskin Belt</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt5.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Embossed Thistle Pattern</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt6.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Embossed Celtic Pattern</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt7.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Embossed Oval Pattern</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt8.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Embossed Interlink Pattern</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt9.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Embossed Gothic Pattern</h3></div>'
	beltHTML += '</li>'
	beltHTML += '<li class="uk-transition-toggle">'
	beltHTML += '<img src="images/belt/belt10.jpg" alt="">'
	beltHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Embossed Criss Cross Pattern</h3></div>'
	beltHTML += '</li>'
	beltHTML += '</ul>'
	beltHTML += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	beltHTML += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	beltHTML += '</div>'
	beltHTML += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	beltHTML += '</div></div></div>'

	var buckleHTML = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Buckles</h1><div uk-slider="finite: true">'
	buckleHTML += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	buckleHTML += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle1.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Celtic Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle2.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Zoomorphic Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle3.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Thistle Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle4.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Thistle-Thistle Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle5.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Z Thistle Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle6.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Z Lion Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle7.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Shaped Thistle</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle8.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Shaped Lion</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle9.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Plain Thistle Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle10.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Plain Lion Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle11.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Plain Stag Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle12.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Plain Masonic Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle13.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Celtic Thistle Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle14.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Celtic Lion Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle15.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Celtic Stag Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle16.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Plain Masonic Chrome</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '<li class="uk-transition-toggle">'
	buckleHTML += '<img src="images/buckle/buckle17.jpg" alt="">'
	buckleHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>WES12 Chrome Enamel</h3></div>'
	buckleHTML += '</li>'
	buckleHTML += '</ul>'
	buckleHTML += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	buckleHTML += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	buckleHTML += '</div>'
	buckleHTML += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	buckleHTML += '</div></div></div>'

	var skeanHTML = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Skean Dhus</h1><div uk-slider="finite: true; offset-bottom: 30">'
	skeanHTML += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	skeanHTML += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean1.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Topaz Stone</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean2.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Blue Stone</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean3.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Am Stone</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean4.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Green Stone</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean5.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Topaz Stone Thistle</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean6.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Blue Stone Thistle</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean7.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Am Stone Thistle</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean8.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Pip Top</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean9.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SK-T</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean10.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>SK-C</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean11.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Topaz Stone Thistle Antique</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean12.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Blue Stone Thistle Antique</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean13.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Am Stone Thistle Antique</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean14.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Green Stone Thistle Antique</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '<li class="uk-transition-toggle">'
	skeanHTML += '<img src="images/skean/skean15.jpg" alt="">'
	skeanHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Green Stone Shamrock</h3></div>'
	skeanHTML += '</li>'
	skeanHTML += '</ul>'
	skeanHTML += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	skeanHTML += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	skeanHTML += '</div>'
	skeanHTML += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	skeanHTML += '</div></div></div>'

	var pinHTML = '<div class="uk-section uk-section-large"><div class="uk-container"><h1 id="subhead">Kilt Pins</h1><div uk-slider="finite: true">'
	pinHTML += '<div class="uk-position-relative uk-visible-toggle uk-light">'
	pinHTML += '<ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-grid">'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin1.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Sword</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin2.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Thistle</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin3.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Crest Thistle</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin4.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Crest Lion</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin5.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Thistle Antique</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin6.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Large Thistle Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin7.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Viking Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin8.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Large Knot Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin9.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Northumberland Cross</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin10.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Stag And Hound</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin11.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Maple Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin12.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Stag Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin13.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Sword Thistle Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin14.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>2-Thistle Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin15.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Oval Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '<li class="uk-transition-toggle">'
	pinHTML += '<img src="images/pin/pin16.jpg" alt="">'
	pinHTML += '<div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom"><h3>Plain Sword Bulldog</h3></div>'
	pinHTML += '</li>'
	pinHTML += '</ul>'
	pinHTML += '<a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>'
	pinHTML += '<a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>'
	pinHTML += '</div>'
	pinHTML += '<ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>'
	pinHTML += '</div></div></div>'
	$("#mbod").html(aboutUsHTML);

	$( ".menubut" ).click(function( event ) {
		if(!$(this).children().text().startsWith("Products") && !$(this).hasClass("uk-active")){
			$(".menubut").removeClass("uk-active");
			$(".menubut").children().removeClass("uk-active");
			$(this).addClass("uk-active");


			if($(this).children().text() == "Services") {
				$("#mbod").html(servicesHTML);
			}
			else if($(this).children().text() == "Info") {
				$("#mbod").html(infoHTML);
			}
			else if($(this).children().text() == "About Us") {
				$("#mbod").html(aboutUsHTML);
			}
			if($(this).children().text().startsWith("Dress")) {
				$("#mbod").html(classySporran);
				$(this).addClass("uk-active");
				$("#productsNav").addClass("uk-active");
			}			
			if($(this).children().text().startsWith("Semi")) {
				$("#mbod").html(semiSporran);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Day")) {
				$("#mbod").html(daySporran);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Boys")) {
				$("#mbod").html(boySporran);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Tartan")) {
				$("#mbod").html(tartanHTML);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Belt")) {
				$("#mbod").html(beltHTML);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Buckle")) {
				$("#mbod").html(buckleHTML);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Skean")) {
				$("#mbod").html(skeanHTML);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			if($(this).children().text().startsWith("Kilt Pin")) {
				$("#mbod").html(pinHTML);
				$(this).children().addClass("uk-active")
				$("#productsNav").addClass("uk-active");
			}
			console.log("childen text "+ $(this).children().text());
		}
	});

	$("#productsNav").hover(
		function() {
			$(".uk-navbar-dropdown").addClass("block");
		}, function() {
			$(".uk-navbar-dropdown").removeClass("block");
		});
	$(".uk-navbar-dropdown").hover(
		function() {
			$(".uk-navbar-dropdown").addClass("block");
		}, function() {
			$(".uk-navbar-dropdown").removeClass("block");
		});
});